USE "Testdb" 
GO
ALTER DATABASE "testdb" SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE "testdb" COLLATE Latin1_General_CS_AS;

USE "Testdb" 
ALTER DATABASE "testdb" SET MULTI_USER
GO




